// src/components/Button.svelte
<script lang="ts">
	import Spinner from "./icons/Spinner.svelte";
    import clsx from 'clsx'
    
    export let href: string | null | undefined = null
    export let type = 'button'
    export let loading = false
    export let disabled = false
    export let unstyled = false
    export let bg = 'bg-black disabled:bg-gray-200'
    export let color = 'text-white'
    export let shadow: string | boolean = 'not-disabled:shadow not-disabled:hover:-translate-y-1 not-disabled:hover:shadow-elevated not-disabled:active:shadow not-disabled:active:translate-y-0'
    export let rounded = 'rounded-2xl'
    export let padding = 'px-6 py-4'
    export let width = 'w-full'
    export let text = 'text-lg'
    export let align = 'text-center'
    export let font = 'font-medium'
    let cls = ''
    export { cls as class }
</script>

<svelte:element this={href ? 'a' : 'button'} {href} disabled={loading || disabled} {type} on:click
    class={clsx(cls, 'overlap-inline justify-items-center', !unstyled && [width, bg, color, align, shadow, padding, rounded, text, font, width, 'whitespace-nowrap relative transition-all active:transition-none'])}
>
    <span class="block w-full" class:invisible={loading}><slot /></span>
    {#if loading}<Spinner class="h-5" />{/if}
</svelte:element>

// components/Button.tsx
import clsx from "clsx"
import React, { PropsWithChildren } from "react"
import Spinner from "./icons/Spinner"
import Shadow from "./Shadow"

type ButtonProps = PropsWithChildren & 
    {
        shadow?: boolean,
        loading?: boolean,
        fullWidth?: boolean,

    } & JSX.IntrinsicElements['button']

export default React.forwardRef<HTMLButtonElement, ButtonProps>((
  { shadow = false, loading = false, fullWidth = false, children, className, ...props },
  ref,
) => {
    return (
        <div className={clsx(className, 'round-2xl relative', fullWidth ? 'w-full' : 'w-min')}>
            {shadow && <Shadow className="top-1.5 left-1" />}
            <button
                {...(props as JSX.IntrinsicElements['button'])} 
                disabled={loading}
                className={clsx(
                    fullWidth ? 'w-full' : 'w-min',
                    'bg-dark text-white whitespace-nowrap relative rounded text-lg px-5 py-4 transition-transform font-medium',
                    {
                        'cursor-not-allowed': loading,
                        'hover:-translate-y-1 active:translate-y-0 active:transition-none': shadow && !loading
                    }
                )}
                ref={ref}
            >
                {children}
                {loading && <Spinner className="inline-block align-middle text-white" />}
            </button>
        </div>
    )
})
