// components/forms/Button.svelte
<script lang="ts">
	import { browser } from '$app/environment'
	import clsx, { type ClassValue } from 'clsx'
	import Spinner from '../icons/Spinner.svelte'
	import omit from 'lodash/omit'
	import { getFormByIdOrContext } from './Form.svelte'

	export let as = 'button'
	export let href: string | null | undefined = null
	export let formaction: string | undefined = undefined
	export let name: string | undefined = undefined
	export let loading = false
	export let disabled = false
	export let unstyled = false
	export let bg: ClassValue = 'bg-black disabled:bg-gray-300'
	export let color: ClassValue = 'text-white'
	export let shadow: ClassValue =
		'not-disabled:shadow not-disabled:hover:-translate-y-1 not-disabled:hover:shadow-elevated not-disabled:active:shadow not-disabled:active:translate-y-0'
	export let rounded: ClassValue = 'rounded-2xl'
	export let padding: ClassValue = 'px-6 py-4'
	export let width: ClassValue = 'w-full'
	export let textSize: ClassValue = 'text-lg'
	export let align: ClassValue = 'text-center'
	export let font: ClassValue = 'font-medium'
	export let overlap: ClassValue = 'overlap-inline'
	let cls = ''
	export { cls as class }
	let formId: string | undefined = undefined
	export { formId as form }

	$: form = getFormByIdOrContext(formId)
	$: formLoading = form?.loading
	$: formInvalids = form?.invalid
</script>

<svelte:element
	this={href ? 'a' : as}
	{href}
	{...$$restProps}
	disabled={loading ||
		disabled ||
		$formLoading ||
		(browser &&
			$formInvalids &&
			Object.keys(name ? omit($formInvalids, name) : $formInvalids).length > 0)}
	{name}
	on:click
	{formaction}
	form={formId}
	class={clsx(
		cls,
		overlap,
		'items-center justify-items-center',
		!unstyled && [
			width,
			bg,
			color,
			align,
			shadow,
			padding,
			rounded,
			textSize,
			font,
			width,
			'whitespace-nowrap transition-all active:transition-none'
		]
	)}
>
	<span class="block w-full" class:invisible={loading || $formLoading}
		><slot /></span
	>
	{#if loading || $formLoading}<Spinner class="h-5" />{/if}
</svelte:element>

// components/Button.tsx
import clsx from "clsx"
import React, { PropsWithChildren } from "react"
import Spinner from "./icons/Spinner"
import Shadow from "./Shadow"

type ButtonProps = PropsWithChildren & 
    {
        shadow?: boolean,
        loading?: boolean,
        fullWidth?: boolean,

    } & JSX.IntrinsicElements['button']

export default React.forwardRef<HTMLButtonElement, ButtonProps>((
  { shadow = false, loading = false, fullWidth = false, children, className, ...props },
  ref,
) => {
    return (
        <div className={clsx(className, 'round-2xl relative', fullWidth ? 'w-full' : 'w-min')}>
            {shadow && <Shadow className="top-1.5 left-1" />}
            <button
                {...(props as JSX.IntrinsicElements['button'])} 
                disabled={loading}
                className={clsx(
                    fullWidth ? 'w-full' : 'w-min',
                    'bg-dark text-white whitespace-nowrap relative rounded text-lg px-5 py-4 transition-transform font-medium',
                    {
                        'cursor-not-allowed': loading,
                        'hover:-translate-y-1 active:translate-y-0 active:transition-none': shadow && !loading
                    }
                )}
                ref={ref}
            >
                {children}
                {loading && <Spinner className="inline-block align-middle text-white" />}
            </button>
        </div>
    )
})
